// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDsAuJa1jVG16A7wH-sgxM_6NfrspQWw4',
    appId: '1:660995194772:web:6f12ce4f80294e5ea99981',
    messagingSenderId: '660995194772',
    projectId: 'event-planner-notificati-63627',
    authDomain: 'event-planner-notificati-63627.firebaseapp.com',
    storageBucket: 'event-planner-notificati-63627.firebasestorage.app',
    measurementId: 'G-Z88BHTC3X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAewgCDWAZDUQReuMg43GEJh0aqFtYAU_I',
    appId: '1:660995194772:android:a56c9fd6594e2b26a99981',
    messagingSenderId: '660995194772',
    projectId: 'event-planner-notificati-63627',
    storageBucket: 'event-planner-notificati-63627.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-agr-ihCGDT5sLFxEzoNXCt79q5C2XiQ',
    appId: '1:660995194772:ios:6456767175b54688a99981',
    messagingSenderId: '660995194772',
    projectId: 'event-planner-notificati-63627',
    storageBucket: 'event-planner-notificati-63627.firebasestorage.app',
    iosBundleId: 'com.example.eventsmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-agr-ihCGDT5sLFxEzoNXCt79q5C2XiQ',
    appId: '1:660995194772:ios:6456767175b54688a99981',
    messagingSenderId: '660995194772',
    projectId: 'event-planner-notificati-63627',
    storageBucket: 'event-planner-notificati-63627.firebasestorage.app',
    iosBundleId: 'com.example.eventsmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDsAuJa1jVG16A7wH-sgxM_6NfrspQWw4',
    appId: '1:660995194772:web:beeb4ed4dd261dbba99981',
    messagingSenderId: '660995194772',
    projectId: 'event-planner-notificati-63627',
    authDomain: 'event-planner-notificati-63627.firebaseapp.com',
    storageBucket: 'event-planner-notificati-63627.firebasestorage.app',
    measurementId: 'G-CZCTKTPLML',
  );
}
